apiVersion: "v1"
kind: Namespace
metadata:
  name: pizza-ns
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-info
  namespace: pizza-ns
spec:
  type: LoadBalancer
  selector:
    app: pizza-info
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pizza-info
  namespace: pizza-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-info
  namespace: pizza-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-info
  template:
    metadata:
      name: pizza-info
      namespace: pizza-ns
      labels:
        app: pizza-info
    spec:
      containers:
        - name: pizza-info
          image: ghcr.io/grafana/quickpizza-local:latest
          ports:
            - containerPort: 3333
              name: http
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name                
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
      serviceAccountName: pizza-info