name: Build and push Docker images
on:
  release:
    types:
      - published
jobs:
  all:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set version
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const tag_no_v = tag.replace('v', '')
            core.setOutput('tag', tag)
            core.setOutput('tag-no-v', tag_no_v)
      - name: Build Docker image and push to the Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: |
            ghcr.io/quickpizza-base:${{ steps.set_version.outputs.tag-no-v }}, ghcr.io/quickpizza-base:latest
          build-args: TARGETARCH=amd64
      - name: Build Docker image and push to the Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/quickpizza-local:${{ steps.set_version.outputs.tag-no-v }}, ghcr.io/quickpizza-local:latest
          build-args: TARGETARCH=amd64